function m(b,a,c,d){b.m.lb(b.pb,a,c,d)}function n(b,a,c,d){b.m.da?m(b,a,c,d):b.m.Re()._OnMessageFromDOM({type:"event",component:b.pb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function aa(b,a,c){b.m.B(b.pb,a,c)}function ba(b,a){for(const [c,d]of a)aa(b,c,d)}function q(b){b.Ub||(b.m.Bc(b.ge),b.Ub=!0)}window.rc=class{constructor(b,a){this.m=b;this.pb=a;this.Ub=!1;this.ge=()=>this.Oa()}od(){}Oa(){}};
window.Cf=class{constructor(){this.jd=-1}j(){-1!==this.jd&&(self.clearTimeout(this.jd),this.jd=-1)}};"use strict";class ca{constructor(b){this.sb=b;this.Qc=!1;this.Xc=!0;this.ub=this.pa=this.kd=-1}}
function da(b,a){const c=a.elementId,d=b.sd(c,a),e=new ca(d);b.Ha.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Xc=!!a.isVisible;d.addEventListener("focus",()=>{ea(b,"elem-focused",c)});d.addEventListener("blur",()=>{ea(b,"elem-blurred",c)});const f=a.htmlIndex;e.kd=f;e.ub=a.htmlZIndex;b.Ra&&(a=b.m.sc(f),e.pa=a,b.m.Jb(a).appendChild(d))}function fa(b,a){aa(b,"get-element",c=>{const d=v(b,c.elementId);return a(d,c)})}
function v(b,a){b=b.Ha.get(a);if(!b)throw Error(`no element with id ${a}`);return b.sb}function ea(b,a,c){var d;d||(d={});d.elementId=c;m(b,a,d)}
window.qc=class extends self.rc{constructor(b){super(b,"progress-bar");this.Ha=new Map;this.Ra=!0;ba(this,[["create",a=>da(this,a)],["destroy",a=>{a=a.elementId;const c=v(this,a);this.Ra&&c.parentElement.removeChild(c);this.Ha.delete(a)}],["set-visible",a=>{if(this.Ra){var c=this.Ha.get(a.elementId),d=c.sb;c.Qc?d.style.display=a.isVisible?"":"none":c.Xc=!!a.isVisible}}],["update-position",a=>{if(this.Ra){var c=this.Ha.get(a.elementId),d=c.sb,e=this.m;d.style.left=a.left+"px";d.style.top=a.top+"px";
d.style.width=a.width+"px";d.style.height=a.height+"px";var f=a.fontSize;null!==f&&(d.style.fontSize=f+"em");f=a.htmlIndex;c.kd=f;f=e.sc(f);f!==c.pa&&(d.remove(),e.Jb(f).appendChild(d),c.pa=f,e.Kc());a=a.htmlZIndex;a!==c.ub&&(c.ub=a,e.Kc());c.Qc||(c.Qc=!0,c.Xc&&(d.style.display=""))}}],["update-state",a=>{const c=v(this,a.elementId);this.Ac(c,a)}],["focus",a=>{const c=v(this,a.elementId);a.focus?c.focus():c.blur()}],["set-css-style",a=>{const c=v(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?
c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{v(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{v(this,a.elementId).removeAttribute(a.name)}]]);fa(this,a=>a)}sd(){throw Error("required override");}Ac(){throw Error("required override");}};"use strict";const ha=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),w=/android/i.test(navigator.userAgent);let ia=0;
function x(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.sf?new Promise(c=>{const d="c3_resolve_"+ia;++ia;self[d]=c;a.textContent=b.wf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ja(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let y=new Audio;
const ka={"audio/webm; codecs=opus":!!y.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!y.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!y.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!y.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!y.canPlayType("audio/mp4"),"audio/mpeg":!!y.canPlayType("audio/mpeg")};y=null;async function na(b){b=await oa(b);return(new TextDecoder("utf-8")).decode(b)}
function oa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const z=[];let B=0;window.RealFile=window.File;const C=[],E=new Map,F=new Map;let pa=0;const qa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");qa.push(b)};const ra=new Set(["cordova","playable-ad","instant-games"]);let sa=!1;
window.Mb=class b{constructor(a){this.da=a.yf;this.xa=null;this.aa="";this.ab=a.vf;this.Hb={};this.Va=this.ua=null;this.Ta=[];this.ma=null;this.Ud=!0;this.M=[];this.cd=[];this.dd=!1;this.he=()=>this.Pe();this.Uc=!1;this.Od=0;this.wb=null;this.$a=-1;this.nf=()=>this.$e();this.Eb=new Set;this.ld=null;this.ie=[];this.A=a.je;this.Vb="file"===location.protocol.substr(0,4);if("playable-ad"===this.A||"instant-games"===this.A)this.da=!1;if("cordova"===this.A&&this.da&&w){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.da=!1)}this.Ma()?self.chrome.webview.addEventListener("message",c=>this.Dd(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.Dd(c));this.Yb=this.ra=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.df(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Ve());this.B("runtime","cordova-fetch-local-file",c=>this.We(c));this.B("runtime","create-job-worker",()=>this.Xe());this.B("runtime","send-wrapper-extension-message",c=>this.cf(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.Bd(a)):this.Bd(a)}j(){this.Cc();this.xa&&(this.xa=this.xa.onmessage=null);this.ua&&(this.ua.terminate(),this.ua=null);this.Va&&(this.Va.j(),this.Va=null);for(const {canvas:a,
eb:c}of this.M)a.remove(),c.remove();this.M.length=0}Be(){return this.M[0].canvas}sc(a){return Math.min(a,this.M.length-1)}Jb(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].eb}Fe(){return ha&&"cordova"===this.A}jb(){const a=navigator.userAgent;return ha&&ra.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}De(){return w}ud(){return w&&ra.has(this.A)}wd(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}Ma(){return this.wd()||"xbox-uwp-webview2"===this.A}async Bd(a){this.da&&!await ja()&&(this.da=!1);"macos-wkwebview"===this.A?this.mb({type:"ready"}):this.Ma()&&(this.ff(),this.ie=(await this.Ue()).registeredComponentIds);if("playable-ad"===this.A){this.ra=self.c3_base64files;this.Yb={};await this.Me();for(let d=0,e=a.cb.length;d<e;++d){var c=a.cb[d];this.Yb.hasOwnProperty(c)?a.cb[d]={sf:!0,wf:this.Yb[c]}:this.ra.hasOwnProperty(c)&&(a.cb[d]=URL.createObjectURL(this.ra[c]))}a.mc=
[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Bc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.uf?this.aa=a.uf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Af&&(this.Hb=a.Af);c=new MessageChannel;this.xa=c.port1;this.xa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ze(d));this.wb=
new self.Ge(this);await ta(this.wb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.da?await this.Te(a,c.port2):await this.Se(a,c.port2)}Ec(a){a=this.Hb.hasOwnProperty(a)?this.Hb[a]:a.endsWith("/workermain.js")&&this.Hb.hasOwnProperty("workermain.js")?this.Hb["workermain.js"]:"playable-ad"===
this.A&&this.ra.hasOwnProperty(a)?this.ra[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async pc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Vb)return a=await this.Ib(d.rf?a:this.ab+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}oa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}Ad(a){var c=this.aa,d=location.href,e=this.oa(),f=this.ga(),g=window.devicePixelRatio,h=b.ib(),k=a.Ff,l=window.cr_previewImageBlobs||this.ra,p=window.cr_previewProjectFileBlobs,r=window.cr_previewProjectFiles,t=window.cr_swClientId||"";a=a.je;var u=(new URLSearchParams(self.location.search)).has("debug"),A=this.wb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,
projectData:k,previewImageBlobs:l,previewProjectFileBlobs:p,previewProjectFileSWUrls:r,swClientId:t,exportType:a,isDebug:u,ife:!!self.Ef,jobScheduler:{inputPort:A.Tc,outputPort:A.bd,maxNumWorkers:A.kf},supportedAudioFormats:ka,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ab+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ab+"opus.wasm.wasm",isFileProtocol:this.Vb,isiOSCordova:this.Fe(),isiOSWebView:this.jb(),isWindowsWebView2:this.wd(),isAnyWebView2Wrapper:this.Ma(),wrapperComponentIds:this.ie,
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Te(a,c){const d=this.Ec(a.zf);"preview"===this.A?(this.ua=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.ua.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.ua.addEventListener("message",r);this.ua.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.ua=await this.pc(d,this.aa,{type:"module",name:"Runtime",rf:!0});
const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,eb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.mc||[],k=a.cb;h=await Promise.all(h.map(l=>this.Pa(l)));k=await Promise.all(k.map(l=>this.Pa(l)));if("cordova"===this.A)for(let l=0,p=a.lc.length;l<p;++l){const r=
a.lc[l],t=r[0];if(t===a.md||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Pa(t)}this.ua.postMessage(Object.assign(this.Ad(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.lc,mainProjectScript:a.md,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...ua(this.wb)]);this.Ta=C.map(l=>new l(this));this.zd();G(e);va(g);wa(this.ma);self.c3_callFunction=(l,p)=>{var r=this.ma;return r.m.xd(r.pb,"js-invoke-function",
{name:l,params:p})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.lb("runtime","go-to-last-error-script"))}async Se(a,c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,eb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ta=C.map(h=>new h(this));this.zd();G(d);va(e);e=a.cb.map(h=>"string"===
typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.mc)){var f=[...a.mc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.Pa(h)));await Promise.all(e.map(h=>x(h)));e=self.C3_ProjectScriptsStatus;f=a.md;const g=a.lc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Pa(k),await x(k),"preview"!==this.A||e[h]||this.Fd(h,"main script did not run to completion")}catch(l){this.Fd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=
await this.Pa(k),await x(k);"preview"===this.A&&"object"!==typeof self.Bf.Df?(this.Pb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ad(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:qa}),wa(this.ma),this.Cd(),this.Va=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Va,
a))}Fd(a,c){this.Pb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Cd(){this.Pb()}Pb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Xe(){const a=await xa(this.wb);return{outputPort:a,transferables:[a]}}df(a){if(!this.Uc){var c=a.styleWidth+"px",d=a.styleHeight+
"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,eb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Ud&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Ud=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";
a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,eb:p}=this.M.pop();p.remove();this.da&&!d?this.cd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this.da?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=
f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,G(c),va(d),this.M.push({canvas:c,eb:d});for(const l of this.Ta)if(l instanceof window.qc&&l.Ra)for(const p of l.Ha.values())e=l.m.sc(p.kd),f=p.pa,-1!==e&&-1!==f&&e!==f&&(f=p.sb,f.remove(),l.m.Jb(e).appendChild(f),p.pa=e);this.Kc();return{addedCanvases:a,transferables:k}}Ve(){for(const a of this.cd)a.remove();this.cd.length=0}Kc(){this.dd||(this.dd=!0,this.Bc(this.he))}Pe(){this.Ed(this.he);
this.dd=!1;let a=[];for(var c of this.Ta)if(c instanceof window.qc){var d=c.Ra?[...c.Ha.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.pa,l=h.pa;return k!==l?k-l:g.ub-h.ub});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.pa!==c&&(this.yd(c,a.slice(d,e)),c=g.pa,d=e)}d<e&&this.yd(c,a.slice(d,e))}yd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.sb);var d=new Set(c);a=this.Jb(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);
for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Re(){if(this.da)throw Error("not available in worker mode");return this.Va}lb(a,c,d,e,f){this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}xd(a,c,d,e,f){const g=pa++,h=new Promise((k,l)=>{F.set(g,{resolve:k,reject:l})});this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===
c)return this.Ye(a);if("result"===c)this.af(a);else if("runtime-ready"===c)this.bf();else if("alert-error"===c)this.Pb(),alert(a.message);else if("creating-runtime"===c)this.Cd();else throw Error(`unknown message '${c}'`);}Ye(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=E.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Ob(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Ob(f,!0,h)).catch(h=>
{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Ob(f,!1,""+h)}):this.Ob(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Ob(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.xa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}af(a){const c=a.responseId,d=a.isOk;a=a.result;const e=F.get(c);d?e.resolve(a):e.reject(a);F.delete(c)}B(a,c,d){let e=E.get(a);e||(e=new Map,E.set(a,e));
if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static nc(a){if(C.includes(a))throw Error("DOM handler already added");C.push(a)}zd(){for(const a of this.Ta)if("runtime"===a.pb){this.ma=a;return}throw Error("cannot find runtime DOM handler");}Ze(a){this.lb("debugger","message",a)}bf(){for(const a of this.Ta)a.od()}static ib(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||sa)}static Gd(a){sa=!!a}Bc(a){this.Eb.add(a);
this.Jc()}Ed(a){this.Eb.delete(a);0===this.Eb.size&&this.Cc()}Jc(){-1===this.$a&&0<this.Eb.size&&(this.$a=requestAnimationFrame(this.nf))}Cc(){-1!==this.$a&&(cancelAnimationFrame(this.$a),this.$a=-1)}$e(){this.$a=-1;for(const a of this.Eb)a();this.Jc()}Da(a){this.ma.Da(a)}Na(a){this.ma.Na(a)}Ic(){this.ma.Ic()}Nb(a){this.ma.Nb(a)}Ee(){return!!ka["audio/webm; codecs=opus"]}async gf(a){a=await this.xd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ie(a){this.Uc=!0;this.Od=
a}Ce(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}vd(a){return!this.Ce(a)}async Pa(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Vb&&this.vd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Ib(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async We(a){const c=a.filename;switch(a.as){case "text":return await this.Ae(c);case "buffer":return await this.Ib(c);default:throw Error("unsupported type");
}}rd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Ae(a){a=await this.rd(a);return await na(a)}Dc(){if(z.length&&!(8<=B)){B++;var a=z.shift();this.Ne(a.filename,a.xf,a.qf)}}Ib(a){return new Promise((c,d)=>{z.push({filename:a,xf:e=>{B--;this.Dc();c(e)},qf:e=>{B--;this.Dc();d(e)}});this.Dc()})}async Ne(a,c,d){try{const e=await this.rd(a),f=await oa(e);c(f)}catch(e){d(e)}}Dd(a){if("entered-fullscreen"===
a)b.Gd(!0),H(this.ma);else if("exited-fullscreen"===a)b.Gd(!1),H(this.ma);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.ld(a),this.ld=null):"extension-message"===c?this.lb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}cf(a){this.mb({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}mb(a){this.Ma()?window.chrome.webview.postMessage(JSON.stringify(a)):
"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}ff(){window.moveTo=(a,c)=>{this.mb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.mb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Ue(){return this.Ma()?new Promise(a=>{this.ld=a;this.mb({type:"wrapper-init"})}):Promise.resolve()}async Me(){const a=[];for(const [c,d]of Object.entries(this.ra))a.push(this.Le(c,d));
await Promise.all(a)}async Le(a,c){if("object"===typeof c)this.ra[a]=new Blob([c.str],{type:c.type}),this.Yb[a]=c.str;else{let d=await this.Qe(c);d||(d=this.Oe(c));this.ra[a]=d}}async Qe(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Oe(a){a=this.ef(a);return this.Ke(a.data,
a.tf)}ef(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{tf:a,data:d}}Ke(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const I=self.Mb,ya=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},za={dispatchUserScriptEvent:!0},Aa={dispatchRuntimeEvent:!0};function Ba(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ca(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}
async function K(b){b=URL.createObjectURL(b);try{return await Ca(b)}finally{URL.revokeObjectURL(b)}}function Da(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ea(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await K(b);var d=await Da(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await K(b)}
function Fa(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ga=new Set(["input","textarea","datalist","select"]),Ha=new Set(["canvas","body","html"]);function L(b){b.target.tagName&&Ha.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ia(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Ja(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ea(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ka=!1;document.addEventListener("pause",()=>Ka=!0);document.addEventListener("resume",()=>Ka=!1);function G(b){b.addEventListener("selectstart",L);b.addEventListener("gesturehold",L);b.addEventListener("pointerdown",L)}function va(b){b.addEventListener("selectstart",Ia);b.addEventListener("gesturehold",Ia);b.addEventListener("touchstart",Ia)}function wa(b){b.Nd=!0;b.Yc=b.m.oa();b.xb=b.m.ga()}
function H(b){if(!b.ka){var a=I.ib();a&&"any"!==b.gd&&La(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ga()})}}async function Ma(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Na(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Oa(b){return await self.C3_GetSvgImageSize(b.blob)}function Pa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Qa(b){self.setTimeout(()=>{b.Md=!0},1E3);"cordova"===b.m.A?(document.addEventListener("pause",()=>Ra(b,!0)),document.addEventListener("resume",()=>Ra(b,!1))):document.addEventListener("visibilitychange",()=>Ra(b,"hidden"===document.visibilityState));b.bc=!("hidden"!==document.visibilityState&&!Ka);return{isSuspended:b.bc}}
function Sa(b){b.Id||(b.Id=!0,window.addEventListener("deviceorientation",a=>{b.ka||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.ka||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Ta(b){b.Hd||(b.Hd=!0,window.addEventListener("devicemotion",a=>{if(!b.ka){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Ua(b){await Ba(b.url)}
function Va(b,a){b.Pd=a.message;-1===b.Oc&&(b.Oc=setTimeout(()=>{b.Oc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Pd)},250))}function Wa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:I.ib(),innerWidth:b.oa(),innerHeight:b.ga()})}
function Ra(b,a){b.bc!==a&&((b.bc=a)?b.m.Cc():b.m.Jc(),m(b,"visibilitychange",{hidden:a}),!a&&b.m.jb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Xa(b,a,c){"Backspace"===c.key&&L(c);if(b.m.Ma()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(c.key)||c.ctrlKey&&d.includes(c.key))&&c.preventDefault()}b.ka||(d=ya.get(c.code)||c.code,n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},J))}
function M(b,a,c,d){b.ka||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Aa,pageX:c.pageX,pageY:c.pageY+b.Aa,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function N(b,a,c){if(!b.ka){var d=0;"mouse"===c.pointerType&&(d=b.$c);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Aa,pageX:c.pageX,pageY:c.pageY+b.Aa,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},J);"mouse"===c.pointerType&&
(b.$c=c.buttons)}}function Ya(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Aa=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Aa=a))}}
function Za(b,a,c,d){const e=b.oa(),f=b.ga();b.bb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.ib()}):10>d&&$a(b,e,f,d+1)}function $a(b,a,c,d){-1!==b.bb&&clearTimeout(b.bb);b.bb=setTimeout(()=>Za(b,a,c,d),48)}
function La(b){b=b.gd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function ab(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.nc(class extends self.rc{constructor(b){super(b,"runtime");this.Nd=!1;this.bb=-1;this.gd="any";this.bc=this.Hd=this.Id=!1;this.ic=document.createElement("div");this.ic.className="c3-screen-reader-text";this.ic.setAttribute("aria-live","polite");document.body.appendChild(this.ic);this.Ga=null;this.ka=!1;this.Pd="";this.Oc=-1;this.Md=!1;this.Yc=b.oa();this.xb=b.ga();this.Aa=this.Gb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Ma(c));b.B("runtime","raster-svg-image",c=>Na(c));b.B("runtime","get-svg-image-size",c=>Oa(c));b.B("runtime","set-target-orientation",c=>{this.gd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Pa(c));b.B("runtime","go-to-script",c=>Pa(c));b.B("runtime","before-start-ticking",()=>Qa(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ga||(this.Ga=document.createElement("div"),this.Ga.id="inspectOutline",document.body.appendChild(this.Ga));var d=this.Ga;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ga&&(this.Ga.style.display="none")});b.B("runtime","enable-device-orientation",()=>Sa(this));b.B("runtime","enable-device-motion",()=>Ta(this));b.B("runtime","add-stylesheet",c=>Ua(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>{alert(c.message)});b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.ic.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===
d?(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ka=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.m.Be().style.display="";this.m.Ie(c.duration)});b.B("runtime","export-to-video-progress",c=>Va(this,c));b.B("runtime","exported-to-video",c=>{window.pf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.pf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Fa(d)||c.preventDefault()});window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);window.addEventListener("touchstart",L,{passive:!1});window.addEventListener("pointerdown",L,{passive:!1});this.$c=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ja,{passive:!1});window.addEventListener("wheel",Ja,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ka&&this.Nd){var c=this.oa();var d=this.ga();if(this.m.ud()){if(this.Md){if(this.Yc===
c&&d<this.xb){this.Gb=this.xb-d;Ya(this,this.xb,this.Gb);c=void 0;break a}0<this.Gb&&(this.Gb=0,Ya(this,d,this.Gb))}this.Yc=c;this.xb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.ib()});this.m.jb()&&(-1!==this.bb&&clearTimeout(this.bb),Za(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",()=>
H(this));window.addEventListener("fullscreenerror",c=>Wa(this,c));window.addEventListener("webkitfullscreenerror",c=>Wa(this,c));window.addEventListener("mozfullscreenerror",c=>Wa(this,c));if(b.jb()){if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var c=
e.tagName.toLowerCase();var d=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?d.has(e.type.toLowerCase()||"text"):Fa(e)}else c=!1}c||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.Wa=new Set;this.$b=new WeakSet;this.wa=!1}od(){window.addEventListener("focus",()=>{m(this,"window-focus",null,Aa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}m(this,"window-blur",{parentHasFocus:a},Aa);this.$c=0});window.addEventListener("focusin",a=>{a=a.target;(Ga.has(a.tagName.toLowerCase())||Fa(a))&&m(this,"keyboard-blur",null,Aa)});window.addEventListener("keydown",a=>Xa(this,"keydown",a));window.addEventListener("keyup",a=>Xa(this,"keyup",a));window.addEventListener("mousedown",a=>M(this,"mousedown",a,za));window.addEventListener("mousemove",a=>M(this,"mousemove",a,za));window.addEventListener("mouseup",a=>M(this,"mouseup",a,za));window.addEventListener("dblclick",
a=>M(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.ka||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Aa,pageX:a.pageX,pageY:a.pageY+this.Aa,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();ab(a.target)&&document.activeElement&&!ab(document.activeElement)&&document.activeElement.blur();N(this,"pointerdown",a)});this.m.da&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a));window.addEventListener("pointerup",a=>N(this,"pointerup",a));window.addEventListener("pointercancel",a=>N(this,"pointercancel",a));const b=()=>this.Ic();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.m.De()&&!this.m.ud()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Ya(this,this.ga(),navigator.virtualKeyboard.boundingRect.height)}));this.m.jb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}oa(){return this.m.oa()}ga(){return this.m.ga()}Ic(){var b=[...this.Wa];this.Wa.clear();if(!this.wa)for(const a of b)(b=a.play())&&b.catch(()=>{this.$b.has(a)||this.Wa.add(a)})}Da(b){if("function"!==
typeof b.play)throw Error("missing play function");this.$b.delete(b);let a;try{a=b.play()}catch(c){this.Wa.add(b);return}a&&a.catch(()=>{this.$b.has(b)||this.Wa.add(b)})}Na(b){this.Wa.delete(b);this.$b.add(b)}Nb(b){this.wa=!!b}});"use strict";
async function ta(b){if(b.hf)throw Error("already initialised");b.hf=!0;var a=b.ya.Ec(("playable-ad"===b.ya.A?b.ya.ab:"")+"dispatchworker.js");b.Nc=await b.ya.pc(a,b.ob,{name:"DispatchWorker"});a=new MessageChannel;b.Tc=a.port1;b.Nc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.bd=await xa(b)}function ua(b){return[b.Tc,b.bd]}
async function xa(b){const a=b.Vd.length;var c=b.ya.Ec(("playable-ad"===b.ya.A?b.ya.ab:"")+"jobworker.js");c=await b.ya.pc(c,b.ob,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Nc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Vd.push(c);return e.port1}
self.Ge=class{constructor(b){this.ya=b;this.ob=b.aa;this.ob="preview"===b.A?this.ob+"workers/":this.ob+b.ab;this.kf=Math.min(navigator.hardwareConcurrency||2,16);this.Nc=null;this.Vd=[];this.bd=this.Tc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.Mb({yf:!0,zf:"workermain.js",cb:["scripts/c3runtime.js"],lc:[],md:"",vf:"scripts/",mc:[],je:"html5"}));"use strict";function O(b){b.stopPropagation()}
self.Mb.nc(class extends self.qc{constructor(b){super(b)}sd(b,a){const c=document.createElement("progress");c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",O);c.addEventListener("pointermove",O);c.addEventListener("pointerrawupdate",O);c.addEventListener("pointerup",O);c.addEventListener("mousedown",O);c.addEventListener("mouseup",O);c.addEventListener("click",()=>{var d;d||(d={});d.elementId=b;n(this,"click",d)});a.id&&(c.id=
a.id);a.className&&(c.className=a.className);this.Ac(c,a);return c}Ac(b,a){b.title=a.title;const c=a.value;a=a.max;0<a&&0<=c?(b.max=a,b.value=c):(b.removeAttribute("value"),b.removeAttribute("max"))}});"use strict";const bb=180/Math.PI;
async function cb(b,a){if(a.isiOSCordova||a.isSafari)b.dc=!0;b.hd=a.timeScaleMode;b.$d=["equalpower","HRTF","soundfield"][a.panningModel];b.Ld=["linear","inverse","exponential"][a.distanceModel];b.ae=a.refDistance;b.Zd=a.maxDistance;b.ce=a.rolloffFactor;if(b.m.Uc)b.dc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.m.Od)});else{var c={latencyHint:a.latencyHint};b.fe||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");db(b);b.g.onstatechange=()=>{"running"!==b.g.state&&db(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Sa=b.g.createGain();b.Sa.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ba);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function eb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Wd=g.slice(0);gb(b,g);try{b.R=await hb(b,c,d,e,g,f);if(p){Q(b.R,!0);var u=b.R,A=p.innerAngle,la=p.outerAngle,ma=p.outerGain;if(u.vb){ib(u,p.x,p.y,p.z,p.angle);var D=self.fb.Je;u.sa[0]!==D(A)&&
(u.sa[0]=D(A),u.F.coneInnerAngle=D(A));u.sa[1]!==D(la)&&(u.sa[1]=D(la),u.F.coneOuterAngle=D(la));u.sa[2]!==ma&&(u.sa[2]=ma,u.F.coneOuterGain=ma)}p.hasOwnProperty("uid")&&(b.R.qa=p.uid)}else"number"===typeof r&&0!==r?(R(b.R,!0),jb(b.R,r)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,l,t)}catch(vb){console.error("[Construct] Audio: error starting playback: ",vb);return}finally{c=g.join(" ");d=b.Db.get(c);if(!d)throw Error("expected pending tag");d.nd--;0===d.nd&&(d.resolve(),b.Db.delete(c))}q(b)}
async function kb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await lb(b,c);for(const h of S(b,c))if(!h.va){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ka=d;h.Ua=g;h.ee=a}T(b)}async function mb(b,a){const c=a.tags;a=a.rate;await lb(b,c);for(const d of S(b,c))d.la!==a&&(d.la=a,d.Ea())}async function nb(b,a){const c=a.tags;a=a.pos;await lb(b,c);for(const d of S(b,c))d.xc(a)}
async function ob(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await hb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function pb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function qb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.pe(b,...e);else if("delay"===c)d=new self.ne(b,...e);else if("convolution"===c){var g=d=new self.me(b,f.ha,...e),h=a.bufferType;g.Jd=a.bufferOriginalUrl;g.Kd=h}else if("flanger"===c)d=
new self.qe(b,...e);else if("phaser"===c)d=new self.se(b,...e);else if("gain"===c)d=new self.re(b,...e);else if("stereopan"===c)d=new self.ue(b,...e);else if("tremolo"===c)d=new self.ve(b,...e);else if("ringmod"===c)d=new self.te(b,...e);else if("distortion"===c)d=new self.oe(b,...e);else if("compressor"===c)d=new self.le(b,...e);else if("analyser"===c)d=new self.ke(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ja.get(h);l||(l=[],g.ja.set(h,l));d.Td=l.length;d.fd=
h;l.push(d);rb(g,h)}sb(b)}
async function tb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ba()&&1===c||!e.Ba()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ja.values())for(const g of f)g.j();b.ja.clear();b.jc=a.timeScale;b.Pc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ba[e]=d[e];b.g.listener.setOrientation(...b.ba)}b.wa=a.isSilent;b.m.Nb(b.wa);b.Zb=a.masterVolume;b.Sa.gain.value=
b.Zb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>qb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>ub(b,f,c)));T(b)}
async function wb(b,a){try{const c=b.g.suspend(a.time);b.Sd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.m.lb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>xb(d)),b.Sd=!0);await c}catch(c){xb(c)}}
function db(b){b.Tb||(b.Sc=!1,window.addEventListener("pointerup",b.za,!0),window.addEventListener("touchend",b.za,!0),window.addEventListener("click",b.za,!0),window.addEventListener("keydown",b.za,!0),b.Tb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ia)if(g.hb()===c)return await yb(g),g;if(f)return null;if(e&&(b.dc||b.Rd)){f=0;for(let h=0,k=b.ia.length;h<k;++h)g=b.ia[h],b.ia[f]=g,g.Ba()?g.j():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.fe;e&&f&&(b.Rd=!0);c=!e||b.dc||f?new self.ye(b,a,c,d,e,f):new self.we(b,a,c,d,e);b.ia.push(c);await yb(c);b.Yd.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.Yd.add(a));return c}
function zb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Ab(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.ea()}function rb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of Bb(b,a))d=c,e=f.ca||f.F||f.G,e.disconnect(),e.connect(d);b.Ia&&b.Zc===a&&(b.Ia.disconnect(),b.Ia.connect(c))}
function*Bb(b,a){if(a)for(const c of b.H)zb(0<c.na.length?c.na[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Cb(b,a,c){return c?b.m.gf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Db(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.na;var c=a;for(const e of c){c=!1;for(const f of b)if(zb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function hb(b,a,c,d,e,f){for(const g of b.H)if(g.hb()===c&&(g.oc()||f))return g.na=e,g;a=await P(b,a,c,d,f);e="html5"===a.Lc?new self.xe(a.u,a,e):new self.ze(a.u,a,e);b.H.push(e);return e}
function gb(b,a){a=a.join(" ");let c=b.Db.get(a);if(!c){let d=null;c={nd:0,promise:new Promise(e=>d=e),resolve:d};b.Db.set(a,c)}c.nd++}function lb(b,a){return(b=b.Db.get((0===a.length?b.Wd:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Qa.size)q(b);else for(const a of b.H)if(!a.I&&!a.O()){q(b);break}}function Eb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function sb(b){b.Vc||(b.Vc=!0,Promise.resolve().then(()=>Fb(b)))}
function Fb(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.gb());m(b,"fxstate",{fxstate:a});b.Vc=!1}
async function ub(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await hb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Ya[0]=f[0],b.Ya[1]=f[1],b.Ya[2]=f[2],f=d.orient,b.Xa[0]=f[0],b.Xa[1]=f[1],b.Xa[2]=f[2],e.setPosition(...b.Ya),e.setOrientation(...b.Xa),b.sa[0]=d.cia,b.sa[1]=d.coa,b.sa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.qa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),jb(b,d));c.Play(k,l,p,0);a.isPlaying||c.kb();c.Gc(a)}}}function xb(b){console.error("[Audio] Offline rendering error: ",b)}
self.fb=class extends self.rc{constructor(b){super(b,"audio");this.Sa=this.g=null;this.Tb=this.Sc=!1;this.za=()=>{if(!this.Sc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Tb&&(this.Sc=!0,window.removeEventListener("pointerup",this.za,!0),window.removeEventListener("touchend",this.za,!0),window.removeEventListener("click",this.za,!0),window.removeEventListener("keydown",
this.za,!0),this.Tb=!1)}};this.ia=[];this.H=[];this.R=null;this.Wd=[];this.Yd=new Set;this.Xd=-1;this.Db=new Map;this.Zb=1;this.wa=!1;this.hd=0;this.jc=1;this.Pc=0;this.$d="HRTF";this.Ld="inverse";this.ae=600;this.Zd=1E4;this.ce=1;this.$=[0,0,0];this.ba=[0,0,-1,0,1,0];this.Rd=this.dc=!1;this.fe=this.m.Ee();this.ja=new Map;this.Qa=new Set;this.Sd=this.Vc=!1;this.Zc="";this.Ia=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ia&&this.Ia.disconnect();this.Zc=c.toLowerCase();this.Ia=this.g.createMediaStreamSource(a);
this.Ia.connect(Ab(this,this.Zc))};this.Sb=null;self.C3Audio_GetOutputStream=()=>{this.Sb||(this.Sb=this.g.createMediaStreamDestination(),this.Sa.connect(this.Sb));return this.Sb.stream};self.C3Audio_DOMInterface=this;ba(this,[["create-audio-context",a=>cb(this,a)],["play",a=>eb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Ca()}],["stop-all",()=>{for(const a of this.H)a.Ca()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.kb():d.Lb();T(this)}],["set-volume",
a=>{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>kb(this,a)],["set-master-volume",a=>{this.Zb=a.vol;this.Sa.gain.value=this.Zb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Gb(d,a)}],["set-silent",a=>{this.wa=a.isSilent;this.m.Nb(this.wa);for(const c of this.H)c.Qb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.yc(a)}],["set-playback-rate",a=>mb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),jb(d,a)}],["seek",a=>nb(this,a)],["preload",a=>ob(this,a)],["unload",a=>pb(this,a)],["unload-all",()=>{for(const a of this.ia)a.j();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.zc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>qb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ja.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);sb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ja.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ja.delete(a);rb(this,a)}}],["tick",a=>{this.jc=a.timeScale;this.Pc=a.gameTime;this.Xd=a.tickCount;if(0!==this.hd)for(var c of this.H)c.Ea();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ba[0]!==
c[0]||this.ba[1]!==c[1]||this.ba[2]!==c[2]||this.ba[3]!==c[3]||this.ba[4]!==c[4]||this.ba[5]!==c[5])){for(let d=0;6>d;++d)this.ba[d]=c[d];this.g.listener.setOrientation(...this.ba)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.qa===a&&ib(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>tb(this,a)],["offline-render-audio",a=>wb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Sa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Kb(){return this.wa}Da(b){this.m.Da(b)}Na(b){this.m.Na(b)}Oa(){for(var b of this.Qa)b.Oa();
b=this.g.currentTime;for(var a of this.H)a.Oa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.gb());m(this,"state",{tickCount:this.Xd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Qa].map(c=>({tag:c.fd,index:c.Td,peak:c.Za,rms:c.be,binCount:c.l.frequencyBinCount,freqBins:c.Qd}))});0===a.length&&0===this.Qa.size&&this.Ub&&(this.m.Ed(this.ge),this.Ub=!1)}static Je(b){return b*bb}static td(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static He(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.Mb.nc(self.fb);"use strict";function yb(b){b.Xb||(b.Xb=b.Fc());return b.Xb}self.pd=class{constructor(b,a,c,d,e){this.u=b;this.mf=a;this.Ja=c;this.T=d;this.jf=e;this.Lc="";this.Xb=null}j(){this.Xb=this.u=null}Fc(){}V(){return this.u.V()}uc(){return this.mf}hb(){return this.Ja}tc(){return this.T}Ba(){return this.jf}fa(){}};"use strict";
self.we=class extends self.pd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Lc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.yb=this.zb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Cb=this.V().createGain();this.Bb=null;this.L.addEventListener("canplay",()=>{this.zb&&(this.zb(),this.yb=this.zb=null);!this.Bb&&this.L&&(this.Bb=this.V().createMediaElementSource(this.L),this.Bb.connect(this.Cb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ja}' error: `,f);this.yb&&(this.yb(f),this.yb=this.zb=null)})}j(){Db(this.u,this);this.Cb.disconnect();this.Cb=null;this.Bb.disconnect();this.Bb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Fc(){return new Promise((b,a)=>{this.zb=b;this.yb=a;this.L.src=this.Ja})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Hb(b){if(b.Fa)return b.Fa;var a=b.u.m;if("cordova"===a.A&&a.vd(b.Ja)&&a.Vb)b.Fa=await a.Ib(b.Ja);else{a=await fetch(b.Ja);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Fa=await a.arrayBuffer()}}async function Ib(b){if(b.ha)return b.ha;b.ha=await Cb(b.u,b.Fa,b.lf);b.Fa=null}
self.ye=class extends self.pd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Lc="webaudio";this.ha=this.Fa=null;this.lf=!!f}j(){Db(this.u,this);this.ha=this.Fa=null;super.j()}async Fc(){try{await Hb(this),await Ib(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ja}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Jb=0;
function Q(b,a){a=!!a;b.vb!==a&&(b.vb=a,b.vb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.$d,b.F.distanceModel=b.u.Ld,b.F.refDistance=b.u.ae,b.F.maxDistance=b.u.Zd,b.F.rolloffFactor=b.u.ce),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function R(b,a){a=!!a;b.Wb!==a&&(b.Wb=a,b.Wb?(Q(b,!1),b.ca=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ca),b.ca.connect(b.ea())):(b.ca.disconnect(),b.ca=null,b.G.disconnect(),b.G.connect(b.ea())))}function jb(b,a){b.Wb&&b.ed!==a&&(b.ca.pan.value=a,b.ed=a)}function U(b,a){b.Ka=a;b.G.gain.cancelScheduledValues(0);b.Ua=-1;b.G.gain.value=b.vc()}function Gb(b,a){a=!!a;b.va!==a&&(b.va=a,b.Qb())}
function ib(b,a,c,d,e){if(b.vb){var f=b.Ya,g=b.Xa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Wc?b.u.Pc:performance.now()/1E3}
self.qd=class{constructor(b,a,c){this.u=b;this.P=a;this.na=c;this.Rb=Jb++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.vb=!1;this.Ya=[0,0,0];this.Xa=[0,0,0];this.sa=[0,0,0];this.ca=null;this.Wb=!1;this.ed=0;this.I=!0;this.Y=this.ta=this.J=!1;this.Ka=1;this.va=!1;this.la=1;b=this.u.hd;this.Wc=1===b&&!this.Ba()||2===b;this.Ua=this.qa=-1;this.ee=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.ca&&(this.ca.disconnect(),this.ca=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ea(){return Ab(this.u,0<this.na.length?this.na[0]:"")}uc(){return this.P.uc()}hb(){return this.P.hb()}tc(){return this.P.tc()}Ba(){return this.P.Ba()}O(){}oc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}La(){}fa(){return this.P.fa()}Play(){}Ca(){}kb(){}Lb(){}Oa(b){-1!==this.Ua&&b>=this.Ua&&(this.Ua=-1,this.ee&&this.Ca(),Eb(this.u,"fade-ended",this.na,this.Rb))}vc(){const b=this.Ka;return isFinite(b)?b:0}Kb(){return this.u.Kb()}Qb(){}yc(){}Ea(){}xc(){}zc(){}wc(){}gb(){var b=
this.Rb,a=this.na,c=this.fa(),d=-1===this.Ua?this.Ka:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ya,orient:this.Xa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.qa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.La(),playbackRate:this.la,uid:this.qa,bufferOriginalUrl:this.uc(),bufferUrl:"",bufferType:this.tc(),isMusic:this.Ba(),isLooping:this.Y,isMuted:this.va,resumePosition:this.wc(),pan:f,stereoPan:this.ca?
this.ed:null}}Gc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Ea());Gb(this,b.isMuted)}};"use strict";
self.xe=class extends self.qd{constructor(b,a,c){super(b,a,c);this.P.Cb.connect(this.G);this.P.onended=()=>this.Hc()}j(){this.Ca();this.P.Cb.disconnect();super.j()}W(){return this.P.W()}Hc(){this.I=!0;this.qa=-1;Eb(this.u,"ended",this.na,this.Rb)}O(){return this.W().ended}oc(){return this.I?!0:this.O()}La(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);this.va=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.hb()}' to position '${c}': `,e)}this.u.Da(d);this.J=this.I=!1;this.Y=b;this.la=1}Ca(){const b=this.W();b.paused||b.pause();this.u.Na(b);this.I=!0;this.J=!1;this.qa=-1}kb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.Na(b);this.J=!0}}Lb(){!this.J||this.I||this.O()||(this.u.Da(this.W()),this.J=!1)}Qb(){this.W().muted=this.va||this.Kb()}yc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ea(){let b=this.la;this.Wc&&(b*=this.u.jc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}xc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}wc(){return this.La()}zc(b){b?this.IsPlaying()?(this.W().pause(),this.ta=!0):this.ta=!1:this.ta&&(this.u.Da(this.W()),this.ta=!1)}};"use strict";
function W(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.nb=null}
self.ze=class extends self.qd{constructor(b,a,c){super(b,a,c);this.s=null;this.ac=d=>this.Hc(d);this.Rc=!0;this.nb=null;this.S=this.cc=this.ec=0;this.ad=1}j(){this.Ca();W(this);this.ac=null;super.j()}Hc(b){this.J||this.ta||b.target!==this.nb||(this.I=this.Rc=!0,this.qa=-1,W(this),Eb(this.u,"ended",this.na,this.Rb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Rc}oc(){return!this.s||this.I?!0:this.O()}La(){let b;b=this.J?this.S:this.cc+(V(this)-this.ec)*this.la;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.va=!1;this.ad=1;U(this,a);W(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ha;this.s.connect(this.G);this.nb=this.s;this.s.onended=this.ac;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Rc=!1;this.Y=b;this.la=1;this.ec=V(this);this.cc=c}Ca(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.qa=-1}kb(){this.J||this.I||this.O()||(this.S=this.La(),this.Y&&(this.S%=this.fa()),this.J=!0,this.s.stop(0))}Lb(){!this.J||this.I||this.O()||(W(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.nb=this.s,this.s.onended=this.ac,this.s.loop=this.Y,U(this,this.Ka),this.Ea(),this.s.start(0,this.S),this.ec=V(this),this.cc=this.S,this.J=!1)}vc(){return super.vc()*this.ad}Qb(){this.ad=this.va||this.Kb()?0:1;U(this,this.Ka)}yc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ea(){let b=this.la;this.Wc&&(b*=this.u.jc);this.s&&(this.s.playbackRate.value=b)}xc(b){this.I||this.O()||(this.J?this.S=b:(this.kb(),
this.S=b,this.Lb()))}wc(){return this.S}zc(b){b?this.IsPlaying()?(this.ta=!0,this.S=this.La(),this.Y&&(this.S%=this.fa()),this.s.stop(0)):this.ta=!1:this.ta&&(W(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.nb=this.s,this.s.onended=this.ac,this.s.loop=this.Y,U(this,this.Ka),this.Ea(),this.s.start(0,this.S),this.ec=V(this),this.cc=this.S,this.ta=!1)}Gc(b){super.Gc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.V();this.Td=-1;this.T=this.fd="";this.o=null}j(){this.g=null}N(){}U(){}gb(){return{type:this.T,tag:this.fd,params:this.o}}}
self.pe=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.v=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}j(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.ne=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.Ab=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.rb=X(this);this.rb.gain.value=c;this.v.connect(this.Ab);this.v.connect(this.h);this.Ab.connect(this.i);this.Ab.connect(this.X);this.X.connect(this.rb);this.rb.connect(this.Ab)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.Ab.disconnect();
this.X.disconnect();this.rb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.fb.td;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);Y(this,this.rb.gain,e(a),c,d);break;case 5:this.o[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.me=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Kd=this.Jd="";this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.qb=this.g.createConvolver();this.qb.normalize=c;this.qb.buffer=a;this.v.connect(this.qb);this.v.connect(this.h);this.qb.connect(this.i)}j(){this.v.disconnect();this.qb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}gb(){const b=super.gb();b.bufferOriginalUrl=this.Jd;b.bufferUrl="";b.bufferType=this.Kd;return b}};
self.qe=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.v=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.tb=X(this);this.tb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=X(this);this.K.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.tb);this.tb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.tb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;Y(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;Y(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,Y(this,this.tb.gain,a/100,c,d)}}};
self.se=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.v=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=X(this);this.K.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;Y(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,Y(this,this.C.frequency,a,c,d)}}};self.re=class extends Z{constructor(b,a){super(b);this.T="gain";this.o=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.fb.td;switch(b){case 4:this.o[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.ue=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.ve=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=X(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.l.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.te=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.v=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Fb=X(this);this.Fb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Fb.gain);this.C.start(0);this.v.connect(this.Fb);this.v.connect(this.h);this.Fb.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Fb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.oe=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.v=X(this);this.hc=X(this);this.fc=X(this);b=d;.01>b&&(b=.01);this.hc.gain.value=b;this.fc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.kc=this.g.createWaveShaper();this.Mc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Mc[32768+e]=f,this.Mc[32768-
e-1]=-f;this.kc.curve=this.Mc;this.v.connect(this.hc);this.v.connect(this.h);this.hc.connect(this.kc);this.kc.connect(this.fc);this.fc.connect(this.i)}j(){this.v.disconnect();this.hc.disconnect();this.kc.disconnect();this.fc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.le=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.ke=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Qd=new Float32Array(this.l.frequencyBinCount);this.de=new Uint8Array(a);this.be=this.Za=0;b=this.u;b.Qa.add(this);T(b)}j(){this.u.Qa.delete(this);this.l.disconnect();super.j()}Oa(){this.l.getFloatFrequencyData(this.Qd);this.l.getByteTimeDomainData(this.de);const b=this.l.fftSize;let a=this.Za=0;for(var c=0;c<b;++c){let d=(this.de[c]-
128)/128;0>d&&(d=-d);this.Za<d&&(this.Za=d);a+=d*d}c=self.fb.He;this.Za=c(this.Za);this.be=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
